language: node_js
env:
  - CXX=g++-5
addons:
  firefox: "51.0.1"

node_js:
 - "7.6.0"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
