language: node_js
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
  firefox: "latest"
node_js:
 - "6.9.0"
 - "7.6.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.13.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
